apply plugin: 'idea'

idea {
    module {
        inheritOutputDirs = true
    }
}
buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://repo.spongepowered.org/maven' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.40'
    }
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.


group = "hunternif.mc.atlas"
archivesBaseName = "antiqueatlas"

ext.mod_version = "$version_major.$version_minor.$version_patch"
version = "$mc_version-$mod_version"

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    mappings channel: 'stable', version: '39-1.12'

    accessTransformer = files(
            'src/main/resources/META-INF/atlas_at.cfg',
            'libs_at/tfc_at.cfg',
            'libs_at/ImmersiveEngineering_at.cfg'
    )

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            property "fml.coreMods.load", "gloomyfolken.hooklib.minecraft.MainHookLoader"

            property '--usename', 'hohserg'

            mods {
                antiqueatlas {
                    source sourceSets.main
                }
            }
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
    flatDir {
        dirs 'dev_mods'
    }
}

dependencies {
    minecraft ("net.minecraftforge:forge:$mc_version-$forge_version"){

    }

    implementation fg.deobf("abc:crafttweaker2:4.1.20.660")

    implementation fg.deobf("abc:hooklib:3.4")
    implementation fg.deobf("abc:Endothermic:2.1.4")
    implementation fg.deobf("io.gitlab.hohserg.elegant.networking:elegant-networking-1.12:3.15")
    compileOnly fg.deobf("abc:TFC:1.12.2-3")

    compileOnly fg.deobf("abc:ImmersiveEngineering:0.12.107")
    compileOnly fg.deobf("abc:immersivepetroleum-1.12.2:1.1.10")
    //implementation fg.deobf("abc:OptiFine:1.12.2_HD_U_G5")
    //implementation "abc:OptiFine:1.12.2_HD_U_G5_dev"
    /*implementation ("net.minecraft:launchwrapper:"){
        version {
            strictly 'of-2.2'
        }
    }*/

    implementation fg.deobf("dev_mods:ResourceReloader:1.0.2.5")

    //testImplementation "junit:junit:4.+"
}

/*
processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "$mc_version"

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version': project.version, 'mcversion': "$mc_version"
    }

    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
*/

jar.finalizedBy('reobfJar')

jar {
    exclude('hunternif/mc/atlas/FixFuckingBukkitSide.class')
    manifest {
        attributes([
                'FMLAT': 'atlas_at.cfg'
        ])
    }

    archiveAppendix = "no-tfc"

    destinationDirectory = file("$rootDir/production")
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
}

task sourceJar(type: Jar, dependsOn: classes) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

tasks.build.dependsOn('sourceJar', 'deobfJar')

artifacts {
    archives deobfJar
    archives sourceJar
}